import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Appraisal",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-col min-h-screen">
      <Header />
      <div className="flex flex-grow">
        <div className="hidden lg:flex lg:w-64 bg-gray-800">
          <Sidebar />
        </div>
        <div className="flex-grow overflow-y-auto p-3 md:px-4 md:py-2 bg-white">
          {children}
        </div>
      </div>
    </div>
      </body>
    </html>
  );
}



